### ISSUE TITLE
create an example for FirebaseX

### ISSUE THREAD

**Issue by EMI-INDO** [andreszs/cordova-plugin-sms-retriever#10]
**Hi friends can you make me an example with firebasex** plugin https://github.com/dpa99c/cordova-plugin-firebasex#verifyphonenumber

**Thank you**

`var number = '+441234567890';
var timeOutDuration = 60;
var fakeVerificationCode = '123456';
var awaitingSms = false;

FirebasePlugin.verifyPhoneNumber(function(credential) {

    if(credential.instantVerification){
        if(awaitingSms){
            awaitingSms = false;
            // the Android device used auto-retrieval to extract and submit the verification code in the SMS so dismiss user input UI
            dismissUserPromptToInputCode();
        }
        signInWithCredential(credential);
    }else{
        awaitingSms = true;
        promptUserToInputCode() // you need to implement this
            .then(function(userEnteredCode){
                awaitingSms = false;
                credential.code = userEnteredCode; // set the user-entered verification code on the credential object
                signInWithCredential(credential);
            });
    }
}, function(error) {
    console.error("Failed to verify phone number: " + JSON.stringify(error));
}, number, timeOutDuration, fakeVerificationCode);

function signInWithCredential(credential){
    FirebasePlugin.signInWithCredential(credential, function() {
        console.log("Successfully signed in");
    }, function(error) {
        console.error("Failed to sign in", error);
    });
}`

**Comment by andreszs** [comment]
Hi, apparently the author already provides a plugin test app [here](https://github.com/dpa99c/cordova-plugin-firebasex-test).
