### ISSUE TITLE
iOS Support

### ISSUE THREAD

**Issue by ludufre** [andreszs/cordova-plugin-sms-retriever#3]
Hiho, have plan to iOS support? Thanks.

**Comment by andreszs** [comment]
Hi, the **SMS Retriever API** is developed by Google for their Android devices only.

However, if you only need phone number verification, use [cordova-plugin-firebase-authentication](https://github.com/chemerisuk/cordova-plugin-firebase-authentication), which works on both Android and iOS and it features SMS verification (referred as _Firebase authentication_, but you can use it for your own purposes anyway and leave Firebase accounts hidden/unused).
