### ISSUE TITLE
cordova-plugin-sms-retriever

### ISSUE THREAD

**Issue by ompancheshwar** [andreszs/cordova-plugin-sms-retriever#4]
onSMSArrive function not working.

**Comment by jineshh2** [comment]
onSMSArrive not working on given demo code

**Comment by victor-sanchez-ccc** [comment]
onSMSArrive function not working.
cordova log error
W/CordovaPlugin: Attempted to send a second callback for ID: SMSRetriever1014313530

**Comment by andreszs** [comment]
@ompancheshwar what Android version are you using exactly? Is it a real device or emulator?

**Comment by Taxi4you** [comment]
Same for me, I am using real Samsung A71 device.
Also added the google services to platforms/android and installed the google services plugin

**Comment by jineshh2** [comment]
Hi,

Tried to read SMS using Plugin but onSMSArrive Event Listener is not working.

**Comment by andreszs** [comment]
Please update the plugin to latest version 1.1.0 released minutes ago which upgraded Google Play Services to version 15.0.0 and added a missing gms framework to the config.xml file.
