### ISSUE TITLE
StartWatch callback not working

### ISSUE THREAD

**Issue by grandhisubrahmanyam35** [andreszs/cordova-plugin-sms-retriever#5]
I am using this plugin to read OTP of my application. For that, on the dom-ready event, I executed **startWatch** function. After I received the message watcher not printing console statement.

```
SMSRetriever.startWatch(function(msg) {
    // Wait for incoming SMS
    console.log(msg);
}, function(err) {
    // Failed to start watching for SMS
    console.error(err);
});
```

My messgge looks like below.

**Your SMSTEST security code is 9222714**

I am testing in real device android version: 9

**Comment by andreszs** [comment]
Check the sample SMS message from the README file:

> <#> 123ABC is your ExampleApp code. FAw9qCX9VSu

It **must** always begin with <#> and end with the 11-character hash string that identifies your app. Otherwise, the message will be ignored completely by the SMS retriever API.
