### ISSUE TITLE
Cannot install on Cordova Android 9.0.0

### ISSUE THREAD

**Issue by risharde** [andreszs/cordova-plugin-sms-retriever#8]
Via commandline, can this be fixed? 

Installing "cordova-plugin-sms-retriever" for android
Installing "cordova-support-google-services" for android
Plugin doesn't support this project's cordova-android version. cordova-android: 9.0.0, failed version requirement: <9.0.0
Skipping 'cordova-support-google-services' for android
Subproject Path: CordovaLib
Subproject Path: app
Installing "cordova-plugin-sms-retriever" for browser
6.0.0
Plugin dependency "cordova-support-google-services@1.4.1" already fetched, using that version.
Installing "cordova-support-google-services" for browser
6.0.0
Adding cordova-plugin-sms-retriever to package.json

**Comment by andreszs** [comment]
Hi, please reinstall the latest version (1.1.1) which fixed the version requirement and upgraded the Google Play Services version to 15.0.0.
